# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '123' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts', '~> 3.1'
  
  # Pods for 123

  target '123Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '123UITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
